import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../src/components/Footer'
import Header from '../src/components/Header'
import Main from '../src/components/Main'

const Home: NextPage = () => {
  return (
    <div className="w-12/12 h-screen text-white bg-black">
      <Head>
        {/* cabeçalho do HTML esse elemento não é exibido */}
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <Footer />
    </div>
  )
}

export default Home
