import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../src/components/Footer'
import Header from '../src/components/Header'
import Main from '../src/components/Main'
const Home: NextPage = () => {
  return (
    <div className="h-full w-full font-inter bg-bgDefault text-white">
      <Head>
        {/* cabeçalho do HTML esse elemento não é exibido */}
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="w-10/12 mx-auto py-16 border-white border ">
        <Header />
        <Main />
        <Footer />
      </section>
    </div>
  )
}

export default Home
