import type { NextPage } from 'next'
import { useRef } from 'react'
import Head from 'next/head'

import Footer from '../src/components/Footer'
import Header from '../src/components/Header'
import Main from '../src/components/Main'
import Sidebar from '../src/components/Mobile/Sidebar'

const Home: NextPage = () => {
  const refDivMenuMobile = useRef<HTMLDivElement>(null)
  return (
    <div className="h-full w-full font-inter bg-bgDefault text-textPrimary">
      <Head>
        {/* head HTML this element won't viewed */}
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* sidebar for mobile (only xs:screen)*/}
      <Sidebar refDivMenuMobile={refDivMenuMobile} />
      {/* sidebar for mobile (only xs:screen)*/}
      <section className="w-10/12 mx-auto py-16 ">
        <Header refDivMenuMobile={refDivMenuMobile} />
        <Main />
        <Footer />
      </section>
    </div>
  )
}

export default Home
